### ISSUE TITLE
README fail

### ISSUE THREAD

**Issue by NightStalkers** [pvpgamecrash/pvpgamecrash.github.io#11]
U failed on the link in the main README.md

Correction: [talonbragg.com](https://talonbragg.com)

**Comment by pvpgamecrash** [comment]
When I click on that it gives me a 404

**Comment by NightStalkers** [comment]
Try it now

**Comment by NightStalkers** [comment]
Omg this friggin sucks

**Comment by adampbragg** [comment]
I fixed it. You guys were killing me with this.
