### ISSUE TITLE
Breakout : Level 3

### ISSUE THREAD

**Issue by NightStalkers** [pvpgamecrash/pvpgamecrash.github.io#3]
@pvpgamecrash 

When the player gets to level 3, the level starts instantaneously. How about putting a time buffer so that the player gets some time to react instead of starting right away...

[pvpgamecrash.github.io/level3](url)

**Comment by NightStalkers** [comment]
Welp, we can close this now...

**Comment by pvpgamecrash** [comment]
Hey can you add the padding?
