### ISSUE TITLE
Copied

### ISSUE THREAD

**Issue by KingPixil** [pvpgamecrash/pvpgamecrash.github.io#4]
First of all, the breakout game is taken from [MDN](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript), without giving any credit, or customizing/playing around with the code. 

Second, the loader is also copied.

Please explain @pvpgamecrash 😕

**Comment by pvpgamecrash** [comment]
We were getting to the credit part but we are working on other things on the website. Please tell me what your real name is if you want me to get back to you
