### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by NightStalkers** [pvpgamecrash/pvpgamecrash.github.io#9]
## Repo File Cleanup

@pvpgamecrash, @Nightstalkers, @Sidthecoder 

New Branch called cleanup created
Everyone off master branch for 5 days

- Large and unused files are deleted
- Folders are cleaned up
- Files are put into corresponding folders

**Comment by pvpgamecrash** [comment]
We should only have a few files on the outside. In the read me please give a shoutout to [Deathstock Photos](http://deathtothestockphoto.com/) for the images that they let me have on my website [main page](https://pvpgamecrash.github.io)

**Comment by NightStalkers** [comment]
@pvpgamecrash,

Please accpet the pull request I created

**Comment by pvpgamecrash** [comment]
[Pull Request](https://github.com/pvpgamecrash/pvpgamecrash.github.io/pull/10) has been accepted.

**Comment by pvpgamecrash** [comment]
Please tell me if this was the whole clean up.
